title: Shu Wang
logo: /assets/img/logo.png
description: Deep Navigation provides low power and low cost but high resolution positioning technologies.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
